#!/usr/bin/env python3
"""Build static/_redirects from a CSV source list."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def normalize(path: str) -> str:
    path = (path or "").strip()
    if not path:
        return ""
    if not path.startswith("/"):
        path = "/" + path
    return path


def build_redirects(csv_file: Path, output_file: Path) -> int:
    redirects: list[str] = []
    seen: set[tuple[str, str, str]] = set()

    with csv_file.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            source = normalize(row.get("source", ""))
            target = normalize(row.get("target", ""))
            status = (row.get("status") or "301").strip()

            if not source or not target:
                continue

            key = (source, target, status)
            if key in seen:
                continue
            seen.add(key)
            redirects.append(f"{source} {target} {status}")

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with output_file.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# Auto-generated by scripts/generate_redirects.py\n")
        handle.write("# Format: /old-path /new-path 301\n")
        for line in redirects:
            handle.write(f"{line}\n")

    return len(redirects)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate static/_redirects from CSV")
    parser.add_argument("--csv", default="data/legacy-redirects.csv", help="CSV with source,target,status")
    parser.add_argument("--output", default="static/_redirects", help="Output file path")
    args = parser.parse_args()

    count = build_redirects(Path(args.csv), Path(args.output))
    print(f"Wrote {count} redirects to {args.output}")


if __name__ == "__main__":
    main()
